# Generated by Django 4.1.1 on 2022-09-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_rename_fragen_mpcfragen'),
    ]

    operations = [
        migrations.CreateModel(
            name='textfragen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('antwort', models.CharField(max_length=255)),
            ],
        ),
    ]
