# Generated by Django 4.1.1 on 2022-09-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_textfragen'),
    ]

    operations = [
        migrations.CreateModel(
            name='usertests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('anzahlfragen', models.IntegerField()),
                ('richtig', models.IntegerField()),
                ('falsch', models.IntegerField()),
            ],
        ),
    ]
