# Generated by Django 4.1.1 on 2022-09-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_usertests'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpcfragen',
            name='right',
            field=models.IntegerField(default=0),
        ),
    ]
