# Generated by Django 4.1.1 on 2022-10-27 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0005_mpcfragen_right'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mpcfragen',
        ),
        migrations.DeleteModel(
            name='textfragen',
        ),
        migrations.DeleteModel(
            name='usertests',
        ),
    ]
