# Generated by Django 4.1.3 on 2022-11-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0010_questionshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesss',
            name='m',
            field=models.BooleanField(default=None),
        ),
    ]
