# Generated by Django 4.1.3 on 2022-11-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0011_gamesss_m'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesss',
            name='withname',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gamesss',
            name='m',
            field=models.BooleanField(default=False),
        ),
    ]
