# Generated by Django 4.1.3 on 2022-11-15 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0012_gamesss_withname_alter_gamesss_m'),
    ]

    operations = [
        migrations.DeleteModel(
            name='gamesss',
        ),
    ]
