# Generated by Django 4.1.3 on 2022-11-15 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0014_gamesss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesss',
            name='m',
        ),
    ]
