# Generated by Django 4.1.2 on 2022-11-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0018_gamesss_m'),
    ]

    operations = [
        migrations.CreateModel(
            name='casual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('withname', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='duell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('withname', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('withname', models.BooleanField(default=False)),
            ],
        ),
    ]
