# Generated by Django 4.1.2 on 2022-11-17 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0019_casual_duell_ko'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='casual',
            new_name='casuall',
        ),
        migrations.RenameModel(
            old_name='duell',
            new_name='duelll',
        ),
        migrations.RenameModel(
            old_name='ko',
            new_name='koo',
        ),
    ]
