# Generated by Django 4.1.3 on 2022-11-18 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0020_rename_casual_casuall_rename_duell_duelll_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='questions',
        ),
    ]
